# Generated by Django 3.1.6 on 2021-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210222_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
